databases:
  - name: django_ecommerce_db
    databaseName: ecommerce
    user: ecommerce_user
    plan: free

services:
  - type: web
    name: django-ecommerce
    env: docker
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: django_ecommerce_db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: djecommerce.settings.production
